// SPDX-License-Identifier: Apache-2.0

import type { WitnessContext } from '@midnight-ntwrk/compact-runtime';

// NOTE: This import path is generated by the Compact compiler.
import type { Ledger } from './managed/pickup/contract/index.js';

export type PickupPrivateState = {
  readonly issuerSecretKey: Uint8Array;
  readonly patientSecretKey: Uint8Array;
};

export const createPickupPrivateState = (params: PickupPrivateState): PickupPrivateState => params;

export const witnesses = {
  issuerSecretKey: ({ privateState }: WitnessContext<Ledger, PickupPrivateState>): [PickupPrivateState, Uint8Array] => [
    privateState,
    privateState.issuerSecretKey,
  ],
  patientSecretKey: ({ privateState }: WitnessContext<Ledger, PickupPrivateState>): [PickupPrivateState, Uint8Array] => [
    privateState,
    privateState.patientSecretKey,
  ],
};
